6-acceptance-tests
sad16/thinknetica-rails-advanced-qna pull request #13
Opened 2021-03-14 12:24 UTC by sad16

2021-03-14 13:02 UTC, vkurennov requested changes

2021-03-14 13:02 UTC, vkurennov commented on spec/features/questions/answers/destroy_spec.rb
> +      expect(page).to have_content('Delete answer')
это не доказывает, что ссылка работает. сценарий должен быть таким:

зашли на страницу
проверили, что ответ есть на странице
кликнули на ссылку удаления
проверили, что ответа больше нет на странице

2021-03-14 13:02 UTC, vkurennov commented on spec/features/questions/answers/destroy_spec.rb
> +      it_behaves_like 'no link to delete'
ради такой проверки городить шаред-спеку - немного overhead, ну да ладно))

2021-03-14 13:02 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
не забудь написать тесты на метод`User#author_of?`

2021-03-14 22:27 UTC, sad16 commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
Сделал

2021-03-14 22:27 UTC, sad16 commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
Заменил

2021-03-14 22:27 UTC, sad16 commented on app/views/answers/_form.html.slim
> += form_with model: [ @question, Answer.new ], local: true do |f|
Поправил

2021-03-14 22:27 UTC, sad16 commented on app/views/questions/show.html.slim
> +- if @question.user == current_user
Заменил

2021-03-14 22:27 UTC, sad16 commented on app/views/questions/show.html.slim
> +      - if answer.user == current_user
Заменил

2021-03-14 22:27 UTC, sad16 commented on spec/controllers/answers_controller_spec.rb
> +        expect { subject }.to change(question.answers, :count).by(0)
Поправил

2021-03-14 22:27 UTC, sad16 commented on spec/features/questions/answers/create_spec.rb
> +      expect(page).to have_content('The answer has been successfully created')
Поправил

2021-03-14 22:27 UTC, sad16 commented on spec/features/questions/answers/destroy_spec.rb
> +      expect(page).to have_content('Delete answer')
Поправил

2021-03-14 22:28 UTC, sad16 commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
Написал

2021-03-15 09:58 UTC, vkurennov approved these changes

2021-03-15 09:58 UTC, vkurennov commented on spec/models/user_spec.rb
> +      is_expected.to be true
есть еще классный синтаксис для методов-предикатов вида: `expect(user).to  be_author_of(resource)`
это так, для информации

2021-03-15 10:15 UTC, sad16 commented on spec/models/user_spec.rb
> +      is_expected.to be true
Понял, спасибо, поправил

2021-03-15 10:15 UTC, merged