nested-forms-and-polymorphics
sad16/thinknetica-rails-advanced-qna pull request #20
Opened 2021-04-13 21:21 UTC by sad16

2021-04-14 08:51 UTC, vkurennov requested changes
У тебя упущен важный момент с наградами: нет механизма ее выдачи за лучший ответ. То есть саму награду для вопроса назназить можно, а как она пользоветелю, который дал лучший ответ, попадает - непонятно. 
Нужно это доделать и, конечно, покрыть тестами.

2021-04-14 08:51 UTC, vkurennov commented on spec/factories/rewards.rb
> +    association :question, factory: :question
это можно заменить просто на `question`, если имя ассоциации и фабрики совпадают

2021-04-15 07:06 UTC, sad16 commented on spec/factories/rewards.rb
> +    association :question, factory: :question
Поправил

2021-04-15 07:07 UTC, sad16 commented
> У тебя упущен важный момент с наградами: нет механизма ее выдачи за лучший ответ. То есть саму награду для вопроса назназить можно, а как она пользоветелю, который дал лучший ответ, попадает - непонятно.
> Нужно это доделать и, конечно, покрыть тестами.

Все сделал

2021-04-15 11:16 UTC, vkurennov approved these changes

2021-04-15 12:03 UTC, merged